# Game settings
TITLE = "Sky Hop!"
WIDTH = 280
HEIGHT = 500
FPS = 60

# Player settings
PLAYER_ACCELERATION = 0.5
PLAYER_FRICTION = -0.12
PLAYER_GRAVITY = 0.5

# Platform settings
PLATFORM_MOVING_CHANCE = 10
PLATFORM_MOVING_SPEED = 1

# Enemy settings
ENEMY_SPAWN_CHANCE = 500
ENEMY_MOVING_SPEED = 1
ENEMY_SHOOT_CHANCE = 100
MAX_ENEMIES = 3
MAX_PROJECTILES_PER_ENEMY = 2

# Random Generation settings
RANDOM_WIDTH_MIN = 40
RANDOM_WIDTH_MAX = 100

# Upgrade Settings
BOOST_SPAWN_CHANCE = 100
BOOST_POWER = -50
INVINCIBLE_SPAWN_CHANCE = 200
INVINCIBLE_MINIMUM_DURATION = FPS * 2
INVINCIBLE_MAXIMUM_DURATION = FPS * 10

# SpriteSheet settings
PLAYER_SPRITESHEET = "spritesheet_players.png"
ENEMY_SPRITESHEET = "spritesheet_enemies.png"
PLATFORM_SPRITESHEET = "spritesheet_ground.png"
ITEM_SPRITESHEET = "spritesheet_items.png"
TILES_SPRITESHEET = "spritesheet_tiles.png"

# Colours
RED = (255, 0, 0)
SKY_BLUE = (0, 255, 255)
DARK_SKATE_BLUE = (72, 61, 129)
SALMON = (250, 128, 114)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREY = (78, 78, 80)
MAROON = (149, 7, 64)
